apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: cassandra-api-deployment
spec:
  selector:
    matchLabels:
      app: cassandra-api
  replicas: 1
  template:
    metadata:
      labels:
        app: cassandra-api
    spec:
      containers:
      - name: cassandra-api
        image: gcr.io/spy-crowd/cassandra-api:v0.9.0
        resources:
          limits:
            cpu: "0.2"
          requests:
            cpu: "0.2"
        ports:
        - containerPort: 5000
